import numpy as n
import matplotlib.pyplot as plt
import h5py
import stuffr

def plot_andenes():
    t0=stuffr.date2unix(2020,12,4,13,30,0)
    h=h5py.File("and_head/and-trail-5s.h5","r")
    fig=plt.figure(figsize=(1.5*8,6))
    plt.subplot(121)
    plt.pcolormesh(h["tvec"].value-t0,h["ranges"],n.transpose(10.0*n.log10(h["RTI"])),vmin=0,vmax=40.0,cmap="plasma")
    cb=plt.colorbar()
    cb.set_label("SNR (dB)")
    plt.ylabel("One-way range (km)")
    plt.xlabel("Time\n(s since 2020-12-04 13:30)")
    plt.ylim([345,400])
    plt.subplot(122)
    plt.pcolormesh(h["tvec"].value-t0,h["ranges"],n.transpose(h["DOP"]),vmin=-120,vmax=120.0,cmap="seismic")
    cb=plt.colorbar()
    cb.set_label("Radial velocity (m/s)")
    plt.ylabel("One-way range (km)")
    plt.xlabel("Time\n(s since 2020-12-04 13:30)")
    plt.ylim([345,400])
    plt.tight_layout()
    plt.savefig("figs/and_trail_dop.png")
    plt.show()    
def plot_sod():
    t0=stuffr.date2unix(2020,12,4,13,30,0)
    h=h5py.File("sod_data/sod-trail-5s.h5","r")
    fig=plt.figure(figsize=(1.5*8,6))
    plt.subplot(121)
    plt.pcolormesh(h["tvec"].value-t0,h["ranges"],n.transpose(10.0*n.log10(h["RTI"])),vmin=0,vmax=40.0,cmap="plasma")
    cb=plt.colorbar()
    cb.set_label("SNR (dB)")
    plt.ylabel("One-way range (km)")
    plt.xlabel("Time\n(s since 2020-12-04 13:30)")
    plt.ylim([160,202])    
    plt.subplot(122)
    plt.pcolormesh(h["tvec"].value-t0,h["ranges"],n.transpose(h["DOP"]),vmin=-120,vmax=120.0,cmap="seismic")
    cb=plt.colorbar()
    cb.set_label("Radial velocity (m/s)")
    plt.ylabel("One-way range (km)")
    plt.xlabel("Time\n(s since 2020-12-04 13:30)")
    plt.ylim([160,202])
    plt.tight_layout()
    plt.savefig("figs/and_trail_dop.png")
    plt.show()    
def plot_both():
    t0=stuffr.date2unix(2020,12,4,13,30,0)
    
    h=h5py.File("sod_data/sod-trail-5s.h5","r")
    fig=plt.figure(figsize=(1.5*8,1.5*6))
    plt.subplot(221)
    plt.pcolormesh(h["tvec"].value-t0,h["ranges"],n.transpose(10.0*n.log10(h["RTI"])),vmin=0,vmax=30.0,cmap="plasma")
    cb=plt.colorbar()
    cb.set_label("SNR (dB)")
    plt.ylabel("One-way range (km)")
    plt.xlabel("Time\n(s since 2020-12-04 13:30)")
    plt.ylim([160,202])
    plt.xlim([30,410])        
    plt.subplot(222)
    plt.pcolormesh(h["tvec"].value-t0,h["ranges"],n.transpose(h["DOP"]),vmin=-120,vmax=120.0,cmap="seismic")
    cb=plt.colorbar()
    cb.set_label("Radial velocity (m/s)")
    plt.ylabel("One-way range (km)")
    plt.xlabel("Time\n(s since 2020-12-04 13:30)")
    plt.ylim([160,202])    
    plt.xlim([30,410])            


    h=h5py.File("and_head/and-trail-5s.h5","r")
    plt.subplot(223)
    plt.pcolormesh(h["tvec"].value-t0,h["ranges"],n.transpose(10.0*n.log10(h["RTI"])),vmin=0,vmax=30.0,cmap="plasma")
    cb=plt.colorbar()
    cb.set_label("SNR (dB)")
    plt.ylabel("One-way range (km)")
    plt.xlabel("Time\n(s since 2020-12-04 13:30)")
    plt.ylim([345,400])
    plt.xlim([30,410])                
    plt.subplot(224)
    plt.pcolormesh(h["tvec"].value-t0,h["ranges"],n.transpose(h["DOP"]),vmin=-120,vmax=120.0,cmap="seismic")
    cb=plt.colorbar()
    cb.set_label("Radial velocity (m/s)")
    plt.ylabel("One-way range (km)")
    plt.xlabel("Time\n(s since 2020-12-04 13:30)")
    plt.ylim([345,400])
    plt.xlim([30,410])                
    plt.tight_layout()
    plt.savefig("figs/both_trail_dop.png")

    
    plt.show()    


plot_both()
